[default]
account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
user = "${{ secrets.SNOWFLAKE_USER }}"
password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
role = "${{ secrets.SNOWFLAKE_ROLE }}"
warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
database = "${{ secrets.SNOWFLAKE_DATABASE }}"
schema = "hrdata"
