#!/bin/bash
set -e

SNOWSQL_ACCOUNT="$1"
SNOWSQL_USER="$2"
SNOWSQL_ROLE="$3"
SNOWSQL_WAREHOUSE="$4"
ORIGINAL_DB="$5"
CLONED_DB="$6"
SNOWSQL_PRIVATE_KEY_PATH="$7"

export SNOWFLAKE_PRIVATE_KEY_PATH="$SNOWSQL_PRIVATE_KEY_PATH"

snowsql -a "$SNOWSQL_ACCOUNT" -u "$SNOWSQL_USER" -r "$SNOWSQL_ROLE" -w "$SNOWSQL_WAREHOUSE" -q "
CREATE DATABASE $CLONED_DB CLONE $ORIGINAL_DB;
"

echo "Database cloned successfully: $CLONED_DB"
